apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo-doodba.fullname" . }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
data:
{{- if .Values.config }}
{{ toYaml .Values.config | indent 2 }}
{{- end }}
