apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-doodba.fullname" . }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.odooPassword }}
  odoo-password: {{ .Values.odooPassword | b64enc | quote }}
  {{ else }}
  odoo-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if not .Values.postgresql.enabled }}
    {{ if .Values.postgresql.postgresqlPassword}}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote  }}
    {{ else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
    {{ end }}
  {{ end }}
