{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "odoo-doodba.serviceAccountName" . }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
{{- end -}}
