apiVersion: v2
appVersion: "13.0"
description: Odoo chart for Kubernetes using Tecnativa's Docker odoo base (Doodba)
icon: https://odoocdn.com/openerp_website/static/src/img/assets/png/odoo_logo.png?a=b
name: odoo-doodba
keywords:
  - odoo
  - doodba
version: 1.1.11
maintainers:
- name: Paul Catinean
  email: pca@pledra.com
  url: http://pledra.com
dependencies:
- name: postgresql
  condition: postgresql.enabled,
  version: 16.13.x
  repository: https://charts.bitnami.com/bitnami
- name: redis
  condition: redis.enabled,
  version: 10.6.15
  repository: https://charts.bitnami.com/bitnami
- name: common
  version: 0.x.x
  repository: https://charts.bitnami.com/bitnami
