apiVersion: v2
appVersion: "15.0"
description: Odoo chart for Kubernetes using Tecnativa's Docker odoo base (Doodba)
icon: https://odoocdn.com/openerp_website/static/src/img/assets/png/odoo_logo.png?a=b
name: odoo-doodba
keywords:
  - odoo
  - doodba
version: 3.0.0
maintainers:
- name: PCatinean
  email: pca@pledra.com
  url: https://github.com/pledra/odoo-cloud-addons
dependencies:
- name: postgresql
  condition: postgresql.enabled,
  version: 16.x.x
  repository: https://charts.bitnami.com/bitnami
- name: redis
  condition: redis.enabled,
  version: 20.x.x
  repository: https://charts.bitnami.com/bitnami
- name: common
  version: 2.x.x
  repository: https://charts.bitnami.com/bitnami
