name: Generate Helm Chart Readme

on:
  pull_request:
    branches:
      - master
    paths:
      - 'helm-charts/*/values.yaml'

jobs:
  generate-chart-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v2
        with:
          repository: 'bitnami-labs/readme-generator-for-helm'
          ref: '967764dacee72c05fc5d01c84c13ebb5dab7ac8b'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - name: Checkout pledra/helm-charts
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: odoo-cloud-addons
          # token: ${{ secrets.PLEDRA_BOT_TOKEN }}

      - name: Execute readme-generator-for-helm
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$URL")
          files_changed="$(echo $files_changed_data | jq -r '.[] | .filename')"
          # Adding || true to avoid "Process exited with code 1" errors
          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "helm-charts/[^/]*" | sort | uniq || true)"
          for chart in ${charts_dirs_changed}; do
            echo "Updating README.md for ${chart}"
            readme-generator-for-helm/bin/index.js --values "odoo-cloud-addons/${chart}/values.yaml" --readme "odoo-cloud-addons/${chart}/README.md"
          done

      - name: Push changes
        run: |
          # Push all the changes
          cd helm-charts
          if git status -s | grep helm-charts; then
            git config user.name "Pledra Containers"
            git config user.email "bot@pledra.com"
            git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push
          fi